library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('system/', include('system.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
]

library/system/urls.py
from django.urls import path

from . import views

app_name = 'system'
urlpatterns = [
    path('', views.index, name='index'),
    path('searchbook/', views.searchbook, name='searchbook'),
    path('searchunavbooks/', views.searchunavbooks, name='searchunavbooks'),
    path('searchrevbooks/', views.searchrevbooks, name='searchrevbooks'),
    path('searchtitleordered/', views.searchtitleordered, name='searchtitleordered'),
    path('searchtitlerevordered/', views.searchtitlerevordered, name='searchtitlerevordered'),
    path('searchuser/', views.searchuser, name='searchuser'),
    path('searchuserordered/', views.searchuserordered, name='searchuserordered'),
    path('searchuserrevordered/', views.searchuserrevordered, name='searchuserrevordered'),
    path('searchuserbr/', views.searchuserbr, name='searchuserbr'),
    path('addbook/', views.addbook, name='addbook'),
    path('<int:book_id>/editbook/', views.editbook, name='editbook'),
    path('<int:book_id>/removebook/', views.removebook, name='removebook'),
    path('<int:book_id>/returnbook/', views.returnbook, name='returnbook'),
    path('<int:book_id>/lendbook/', views.lendbook, name='lendbook'),
    path('<int:book_id>/reservebook/', views.reservebook, name='reservebook'),
    path('<int:book_id>/unreservebook/', views.unreservebook, name='unreservebook'),
    path('<int:book_id>/renewbook/', views.renewbook, name='renewbook'),
    path('<int:user_id>/userprofile/', views.viewuser, name='viewuser'),
    path('adduser/', views.adduser, name='adduser'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
]

library/system/models.py
# models are in models folder

from models import *

library/system/models/book.py
from django.db import models
from django.utils import timezone

from .choices import SECTION_CHOICES, ROW_CHOICES, RACK_CHOICES, RACK_LEVEL_CHOICES
from .user import User
from .bookcategory import BookCategory

class Book(models.Model):
    book_title = models.CharField(max_length=200)
    book_author = models.CharField(max_length=200)
    book_published_date = models.DateTimeField('date published', default=None, null=True, blank=True)
    book_category = models.ForeignKey(BookCategory, default=None, verbose_name="Category", on_delete=models.SET_DEFAULT)
    book_summary = models.TextField(default=None, null=True, blank=True)
    book_active = models.BooleanField(default=True)
    book_position_section = models.CharField(max_length=20, choices=SECTION_CHOICES, default=None,)
    book_position_row = models.CharField(max_length=20, choices=ROW_CHOICES, default=None,)
    book_position_rack = models.CharField(max_length=20, choices=RACK_CHOICES, default=None,)
    book_position_rack_level = models.CharField(max_length=20, choices=RACK_LEVEL_CHOICES, default=None,)
    book_slug = models.CharField(max_length=200, default=1)
    def make_slug(self, book_title):
        slug = book_title.replace(" ", "")
        slug = slug.lower()
        return slug
    def get_date(self):
        return self.modified.date()
    def is_overdue(self):
        if self.book_borrowed:
            duration = timezone.now() - self.book_return_dateline
            if duration > datetime.timedelta(seconds=1):
                return True
            else:
                return False
        else:
            return False
    def can_be_renewed(self):
        if self.book_borrowed:
            duration = self.book_return_dateline - timezone.now()
            if duration < datetime.timedelta(days=5):
                return True
            else:
                return False
        else:
            return False
    def __str__(self):
        return self.book_title

library/system/models/bookcategory.py
from django.db import models
from django.utils import timezone

class BookCategory(models.Model):
    book_category = models.CharField(max_length=200)
    book_category_slug = models.CharField(max_length=200, default=1)
    class Meta():
        verbose_name_plural = "Categories"
    def __str__(self):
        return self.book_category

library/system/forms.py
# forms are in models folder

from forms import *

library/system/forms/bookforms.py
from django import forms
from django.utils import timezone

from system.models.book import Book

class AddBookForm(forms.ModelForm):
    book_published_date = forms.DateField(required = False, widget=forms.SelectDateWidget(years=range(1300, 2100)))
    class Meta():
        model = Book
        fields = ('book_title', 'book_author', 'book_category', 'book_summary', 'book_published_date',
                  'book_position_section', 'book_position_row', 'book_position_rack',
                  'book_position_rack_level')

# class LendBookForm(forms.ModelForm):
#     class Meta():
#         model = Book
#         # fields = ('book_borrowed_by',)

library/system/forms/noticeforms.py
from django import forms
from django.utils import timezone

from system.models.notice import Notice

class AddNoticeForm(forms.ModelForm):
    class Meta():
        model = Notice
        fields = ('notice_title', 'notice_content')
    def save(self, commit=True):
        instance = super(AddNoticeForm, self).save(commit=False)
        instance.published = timezone.now()
        if commit:
            instance.save()
        return instance

library/system/views.py
# views are in views folder

from system.views import *

library/system/views/authentication.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login



def login_request(request):
    if request.method == "POST":
        form =  AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}")
                return redirect("system:index")
            else:
                messages.errror(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                  template_name = "system/login.html",
                  context={"form":form})

# @login_required
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("system:index")

library/system/views/bookviews.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

from system.models import Book, Notice
from system.forms import AddBookForm#, LendBookForm

def searchbook(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        query = query.strip()
        if query is not None:
            results = Book.objects.filter(Q(book_title__icontains=query) | Q(book_author__icontains=query) |
                                          Q(book_category__book_category__icontains=query) & Q(book_active=True))
            return render(request = request,
                          template_name = 'system/search_results.html',
                          context={'books': results, 'from':'searchbook'})
        else:
            return render(request = request, template_name = 'system/search_results.html')
    else:
        return render(request = request, template_name ='system/search_results.html')

def searchunavbooks(request):
    results = Book.objects.filter(Q(book_borrowed=1) & Q(book_active=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'books': results, 'from':'searchbook'})

def searchrevbooks(request):
    results = Book.objects.filter(Q(book_reserved=1) & Q(book_active=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'books': results, 'from':'searchbook'})

def searchtitleordered(request):
    results = Book.objects.order_by('book_title').filter(Q(book_active=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'books': results, 'from':'searchbook'})

def searchtitlerevordered(request):
    results = Book.objects.order_by('-book_title').filter(Q(book_active=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'books': results, 'from':'searchbook'})

def addbook(request):
    if request.method == "POST":
        form = AddBookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.book_slug = book.make_slug(book.book_title)
            book.save()
            form = AddBookForm()
            messages.success(request, 'Book added.')
            return redirect('system:index')
        else:
            messages.warning(request, 'Book not added')
    else:
        form = AddBookForm()
    return render(request = request,
                  template_name = 'system/form.html',
                  context = {"form":form, "notices":Notice.objects.all(), "from":"addbook"})
# remember the other parameter is linked to urls,
# example: path('<int:book_id>/editbook/', views.editbook, name='editbook'),
def editbook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        form = AddBookForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            messages.success(request, 'Book edited.')
            return redirect('system:index')
    else:
        form = AddBookForm(instance=book)
    return render(request = request,
                  template_name = 'system/form.html',
                  context={'form': form, "notices":Notice.objects.all(), "from":"editbook"})

def returnbook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if book.book_borrowed and book.book_reserved:
        book.book_reservation_end_date = timezone.now() + datetime.timedelta(days=3)
    if book.is_overdue():
        try:
            borrower = User.objects.get(id=book.book_borrowed_by.id)
        except User.DoesNotExists:
            return redirect("system:index")
        borrower.fine += 20
        borrower.save()
    borrower = User.objects.get(id=book.book_borrowed_by.id)
    borrower.has_borrowed = False
    book.book_return_dateline = None
    book.book_returned_date = timezone.now()
    book.book_borrowed_date = None
    book.book_borrowed = False
    book.book_borrowed_by = None
    book.save()
    messages.success(request, 'Book returned.')
    return redirect("system:index")

def renewbook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if not book.is_overdue() and book.can_be_renewed():
        book.book_return_dateline = book.book_return_dateline  + datetime.timedelta(days=14)
        book.save()
        messages.success(request, 'Book renewed.')
        return redirect("system:index")
    elif book.is_overdue():
        messages.error(request, f'Book is overdue, please return and settle any outstanding fine. {book.is_overdue}')
        return redirect("system:index")
    elif not book.can_be_renewed():
        messages.error(request, 'Book can only be renewed after being borrowed more than a week.')
        return redirect("system:index")
    else:
        messages.error(request, 'Book not renewed')
        return redirect("system:index")

def removebook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    book.book_active = False
    book.book_borrowed = False
    book.book_reserved = False
    book.save()
    return render(request = request,
                  template_name = 'system/index.html',
                  context = {"books": Book.objects.all(), "notices":Notice.objects.all()})

def reservebook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    book.book_reserved = True
    book.book_reserved_by = request.user
    book.book_reserved_date = timezone.now()
    book.save()
    return render(request = request,
                  template_name = 'system/index.html',
                  context = {"books": Book.objects.all(), "notices":Notice.objects.all()})

def unreservebookfunc(book):
    book.book_reserved_by = None
    book.book_reserved_date = None
    book.book_reservation_end_date = None
    book.book_reserved = False

def unreservebook(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if book.book_reserved:
        unreservebookfunc(book)
    book.save()
    return render(request = request,
                  template_name = 'system/index.html',
                  context = {"books": Book.objects.all(), "notices":Notice.objects.all()})

def lendbook(request, book_id):
    # book = get_object_or_404(Book, id=book_id)
    # if request.method == "POST":
    #     form = LendBookForm(request.POST, instance=book)
    #     if form.is_valid():
    #         book = form.save(commit=False)
    #         book.book_borrowed_date = timezone.now()
    #         book.book_return_dateline = timezone.now() + datetime.timedelta(days=14)
    #         book.book_borrowed = True
    #         if book.book_reserved:
    #             unreservebookfunc(book)
    #         book.save()
    #         messages.success(request, 'Book lent.')
    #         return redirect('system:index')
    # else:
    #     form = LendBookForm(instance=book)
    return render(request = request,
                  template_name = 'system/form.html',
                  context={'form': form, "notices": Notice.objects.all(), "from":"lendbook", 'book': book})

library/system/views/index.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from system.models import Book, Notice

def index(request):
    if request.user.is_authenticated:
        return render(request = request,
                      template_name = 'system/index.html',
                      context = {"books":Book.objects.all()[:5], "notices":Notice.objects.all()[:5], "from":"index"})
    else:
        return redirect("system:login")

library/system/views/userviews.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages


from system.forms import UserAdminCreationForm
from system.models import Book, User, Notice

def account(request):
    return render(request = request, template_name = 'system/account.html')

def searchuserordered(request):
    results = User.objects.order_by('first_name').filter(Q(member=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'users': results, 'from':'searchuser'})

def searchuserrevordered(request):
    results = User.objects.order_by('-first_name').filter(Q(member=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'users': results, 'from':'searchuser'})

def searchuserbr(request):
    results = User.objects.order_by('-first_name').filter(Q(member=True))
    return render(request = request,
                  template_name = 'system/search_results.html',
                  context={'users': results, 'from':'searchuser'})

def searchuser(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        if query is not None:
            results = User.objects.filter(Q(email__icontains=query) | Q(first_name__icontains=query) | Q(last_name__icontains=query))
            book_borrowed_list = Book.objects.filter(Q(book_borrowed=True))
            return render(request = request,
                          template_name = 'system/search_results.html',
                          context={'users': results, 'booklist': book_borrowed_list, 'from':'searchuser', 'query': query})
        else:
            return render(request = request, template_name = 'system/search_results.html')
    else:
        return render(request = request, template_name ='system/search_results.html')

def adduser(request):
    if request.method == "POST":
        form = UserAdminCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.member = True
            user.save()
            form = UserAdminCreationForm()
            messages.success(request, f'User {user.first_name} {user.last_name} added.')
            return redirect('system:index')
        else:
            messages.warning(request, 'User not added')
    else:
        form = UserAdminCreationForm()
    return render(request = request,
                  template_name = 'system/form.html',
                  context = {"form":form, "notices":Notice.objects.all(), "from":"adduser"})

def viewuser(request, user_id):
    user_viewed = get_object_or_404(User, id=user_id)
    book_borrowed_list = Book.objects.filter(Q(book_borrowed=1) & Q(book_borrowed_by=user_id))
    return render(request = request,
                  template_name = 'system/userprofile.html',
                  context={'user_viewed': user_viewed, "books":book_borrowed_list})

library/system/templates/system/includes/book_list.html
<ul class="list-group">
{% for book in books %}
    {% if book.book_active %}
    <li class="list-group-item" a href="#collapseContent{{ book.book_slug }}" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseContent{{ book.book_slug }}">
        <div class="card-header">
        <h4>{{ book.book_title}}
            <span class="label label-info label-as-badge">
            {{ book.book_position_section }}{{ book.book_position_row }}{{book.book_position_rack }}{{book.book_position_rack_level }}
            </span>
        {% if book.book_borrowed  %}
            <span class="label label-warning label-as-badge"> Unavailable </span>
        {% else %}
            <span class="label label-success label-as-badge"> Available </span>
        {% endif %}
        {% if book.book_borrowed and book.book_reserved %}
            {% if book.book_reserved_by.id == user.id or user.is_admin or user.is_staff %}
                <span class="label label-primary label-as-badge"> Reserved </span>
            {% endif %}
        {% endif %}
        {% if book.is_overdue and user.is_authenticated and user.is_staff or user.is_admin %}
            <span class="label label-danger label-as-badge"> OVERDUE </span>
        {% endif %}
        </h4>
        <p style="font-size: 120%;">
        {% if user.is_staff or user.is_admin  %}
            {% if book.book_borrowed %}
            Borrowed by: {{ book.book_borrowed_by.first_name }} {{ book.book_borrowed_by.last_name }}
            Due: {{ book.book_return_dateline }}
            {% endif %}
            {% if book.book_reserved %}
            <br>
            {% endif %}
        {% endif %}
        {% if book.book_reserved and user.is_staff or user.is_admin or user.id == book.book_reserved_by.id %}
            Reserved by: {{ book.book_reserved_by.first_name }} {{ book.book_reserved_by.last_name }}
            {% if book.book_reservation_end_date %}
                Reservation end: {{ book.book_reservation_end_date }}
            {% endif %}
        {% endif %}
        </p>
        </div>
        <div class="collapse" id="collapseContent{{ book.book_slug }}">
            <div class="card card-body">
                <p>
                {% if book.book_summary %}
                    {{ book.book_summary|safe }}
                {% else %}
                    No summary.
                {% endif %}
                </p>
                <p style="font-size: 90%">Author: {{ book.book_author }}</p>
                <p style="font-size: 90%">Category: {{ book.book_category }}</p>
                <p style="font-size: 70%">Published in {{ book.book_published_date|date:'Y'  }}</p>
                {% if user.is_staff or user.is_admin  %}
                <div>
                    <a href="{% url 'system:editbook' book.id %}" class="btn btn-default disable-collapse">Edit</a>
                    <a href="{% url 'system:removebook' book.id %}" class="btn btn-default disable-collapse">Remove</a>
                    {% if book.book_active and book.book_borrowed %}
                        <a href="{% url 'system:returnbook' book.id %}" class="btn btn-default disable-collapse">Return</a>
                    {% else %}
                        <a href="{% url 'system:lendbook' book.id %}" class="btn btn-default disable-collapse">Lend</a>
                    {% endif%}
                    {% if book.book_active and book.book_borrowed and not book.is_overdue %}
                        <a href="{% url 'system:renewbook' book.id %}" class="btn btn-default disable-collapse">Renew</a>
                    {% endif%}
                    {% if book.book_active and book.book_reserved %}
                        <a href="{% url 'system:unreservebook' book.id %}" class="btn btn-default disable-collapse">Unreserve</a>
                    {% endif %}
                </div>
                {% else %}
                <div>
                    {% if book.book_active and book.book_borrowed == True and book.book_reserved == False and not book.book_borrowed_by.id == user.id %}
                        <a href="{% url 'system:reservebook' book.id %}" class="btn btn-default disable-collapse">Reserve</a>
                    {% elif book.book_active and book.book_borrowed == True and book.book_reserved == True and book.book_reserved_by.id == user.id %}
                        <a href="{% url 'system:unreservebook' book.id %}" class="btn btn-default disable-collapse">Unreserve</a>
                    {% endif%}
                </div>
                {% endif %}
            </div>
        </div>
    </li>
    {% endif %}
{% endfor %}
</ul>

library/system/templates/system/includes/carousel.html
<!-- Carousel -->
<h3><span class="glyphicon glyphicon-modal-window"></span> Synergization</h3>
<div id="side-carousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#side-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#side-carousel" data-slide-to="1"></li>
        <li data-target="#side-carousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <a href="#">
                <img class="img-responsive" src="holder.js/400x300?bg=FF8C00&text=Image%201" alt="">
            </a>
            <div class="carousel-caption">
                <h3>Dramatically Engage</h3>
                <p>Objectively innovate empowered manufactured products whereas parallel platforms.</p>
            </div>
        </div>
        <div class="item">
            <a href="#">
                <img class="img-responsive" src="holder.js/400x300?bg=FF8C00&text=Image%202" alt="">
            </a>
            <div class="carousel-caption">
                <h3>Efficiently Unleash</h3>
                <p>Dramatically maintain clicks-and-mortar solutions without functional solutions.</p>
            </div>
        </div>
        <div class="item">
            <a href="#">
                <img class="img-responsive" src="holder.js/400x300?bg=FF8C00&text=Image%203" alt="">
            </a>
            <div class="carousel-caption">
                <h3>Proactively Pontificate</h3>
                <p>Holistically pontificate installed base portals after maintainable products.</p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#side-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#side-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

library/system/templates/system/includes/menu.html
<!-- Left Column -->
    {% if user.is_authenticated %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <form role="search" method="GET" action="{% url 'system:searchbook' %}" value="{{ request.GET.query }}">
                <div class="form-group">
                    <input type="text" class="form-control" name="query">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search Book</button>
            </form>
        </div>
    </div>
    {% if user.is_active %}
        {% if user.is_staff or user.is_admin %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <form role="search" method="GET" action="{% url 'system:searchuser' %}" value="{{ request.GET.query }}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search User</button>
                </form>
            </div>
        </div>
        {% endif %}
    {% endif %}


    <!-- List-Group Panel -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title"><span class="glyphicon glyphicon-briefcase"></span> Options</h1>
        </div>
        <div class="list-group">
            {% if user.is_active %}
                {% if user.is_staff or user.is_admin %}
                <a href="{% url 'system:addbook' %}" class="list-group-item">Add Book</a>
                <a href="{% url 'system:adduser' %}" class="list-group-item">Add User</a>
                {% elif user.is_member %}
                <a href="#" class="list-group-item">Stub</a>
                <a href="#" class="list-group-item">Stub</a>
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% if user.is_active %}
        {% if user.is_staff or user.is_admin %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><span class="glyphicon glyphicon-lamp"></span> Quick Search</h1>
            </div>
            <div class="list-group">
                <a href="{% url 'system:searchrevbooks' %}" class="list-group-item">Reserved Books</a>
                <a href="{% url 'system:searchunavbooks' %}" class="list-group-item">Unavailable Books</a>
                <a href="#" class="list-group-item">Users</a>
            </div>
        </div>
        {% endif %}
    {% endif %}

    {% endif %}

library/system/templates/system/includes/messaging.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error'%}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            <script>$('.alert').alert()</script>

        {% endif %}
    {% endfor %}

{% endif %}
<!-- <script>M.toast({html: "{{ message }}", classes: 'red rounded', displayLength:10000});</script> -->

library/system/templates/system/includes/navbaritems.html
{% if user.is_authenticated %}
<li class="nav-item"><a class="nav-link text-light" href="{% url 'system:viewuser' user.id %}">
    {% if user.is_active %}
        {% if user.is_librarian %}
        Librarian
        {% elif user.is_member %}
        Member
        {% elif user.is_admin %}
        Admin
        {% else %}
        Active
    {% endif %}
{% endif %}
{{ user.email }}
</a></li>
<li class="nav-item"><a class="nav-link text-light" href="{% url 'system:logout' %}">Logout</a></li>
{% else %}
<!-- <li><a href="{% url 'system:login' %}">Login</a></li> -->
{% endif %}

library/system/templates/system/includes/notice.html
{% load static %}

<h2>Feed:</h2>
{% for notice in notices %}
    <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      <img src="{% static "system/media/elephant.jpeg" %}" class="card-img-top" alt="...">
      <h5 class="card-title">{{ notice.notice_title }}</h5>
    </a>
    <div class="collapse" id="collapseExample">
        <div class="card-body">
            <p class="card-text">{{ notice.notice_content|safe }}</p>
            <p style="font-size: 70%">{{ notice.notice_published }}</p>
        </div>
    </div>
{% endfor %}

library/system/templates/system/includes/searchnavbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
        {% if from == 'index' %}
        <span class="navbar-brand">All Books (only 5 displayed):</span>
        {% elif from == 'searchbook' %}
        <span class="navbar-brand">Search Results:</span>
        {% endif %}
        </div>

        <div class="collapse navbar-collapse  navbar-right" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sort <span class="caret"></span></a>
                <ul class="dropdown-menu">
                {% if from == 'searchbook' or from == 'searchrevbooks' or from == 'searchunavbooks' or from == 'index' %}
                    <li><a href="{% url 'system:searchtitleordered' %}"><span class="glyphicon glyphicon-sort-by-alphabet"></span> Alphabetical</a></li>
                    <li><a href="{% url 'system:searchtitlerevordered' %}"><span class="glyphicon glyphicon-sort-by-alphabet-alt"></span> Reverse Alphabet</a></li>
                {% elif from == 'searchuser' %}
                <li><a href="{% url 'system:searchuserordered' %}"><span class="glyphicon glyphicon-sort-by-alphabet"></span> Alphabetical</a></li>
                <li><a href="{% url 'system:searchuserrevordered' %}"><span class="glyphicon glyphicon-sort-by-alphabet-alt"></span> Reverse Alphabet</a></li>
                {% endif %}
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

library/system/templates/system/includes/user_list.html
<div class="list-group">
{% for user in users %}
    {% if user.is_active and user.is_member %}
        <a href="{% url 'system:viewuser' user.id %}" class="list-group-item">
            {{ user.first_name }} {{ user.last_name }}  {{ user.email }}
            {% for book in booklist %}
                {% if book.book_active and book.book_borrowed and book.book_borrowed_by.id == user.id %}
                    <span class="label label-warning">!</span>
                {% endif %}
            {% endfor %}
        </a>
    {% endif %}
{% endfor %}
</div>